# Generated by Django 3.2.5 on 2021-07-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_address', models.CharField(max_length=230)),
                ('sender_phone_no', models.IntegerField()),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_address', models.CharField(max_length=230)),
                ('receiver_phone_no', models.IntegerField()),
                ('package_name', models.CharField(max_length=100)),
                ('package_desc', models.TextField()),
                ('location_sender', models.CharField(max_length=100)),
                ('location_receiver', models.CharField(max_length=100)),
                ('tracking_code', models.CharField(max_length=32)),
            ],
        ),
    ]
