# Generated by Django 3.2.5 on 2021-07-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_delivery',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
