# Generated by Django 3.2.5 on 2021-08-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_booking_delivery_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_delivery',
            name='receiver_phone_no',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='booking_delivery',
            name='sender_phone_no',
            field=models.CharField(max_length=11),
        ),
    ]
